### ISSUE TITLE
Extra empty lines

### ISSUE THREAD

**Issue by dmitresco** [zattoo/stylelint-config#4]
### Environment
Applying on `google-cast-react-client` project, development env.

### Steps to reproduce

1. Run `stylelint app/**/*.scss --fix`

### Actual behavior
There are a lot of extra empty lines before the first properties in a selector rules, e.g.:

```scss
.loader_bounce__1 {

  margin-right: 0.2em;
  animation-delay: -1.1s;
}
```

### Expected behavior
No extra lines to be added
```scss
.loader_bounce__1 {
  margin-right: 0.2em;
  animation-delay: -1.1s;
}
